version: '3'
services:
    mongo:
        container_name: mongo
        image: mongo:4.0
        volumes:
            - ${MONGO_PERMANENT_FOLDER}:/data/db
        ports:
            - 27017:27017
        restart: always
    web:
        build: .
        container_name: mathlab
        command: bash -c "sleep 10 && npx migrate-mongo up && npm run start:dev"
        environment:
            - NODE_ENV=${NODE_ENV}
        links:
            - mongo
        volumes:
            - .:/app
            - node_modules:/app/node_modules
        ports:
            - 8000:8000
volumes:
    node_modules:
